import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <a href="/">หน้าแรก</a>
        <a href="/about">เกี่ยวกับระบบ</a>
        <a href="/contect">ติดต่อฉัน</a>
        <a href="/student">รายชื่อนักศึกษา</a>
        <a href="/hello">ทักทาย</a>
        {children}
        <hr />
        พัฒนาโดย นายรัก เสมอกัน
        </body>
    </html>
  );
}
